apiVersion: v1
kind: Service
metadata:
  name: {{ values.portalName }}-rhdh
  labels:
    app: {{ values.portalName }}-rhdh
spec:
  type: NodePort
  ports:
  - port: 7007
    targetPort: 7007
    protocol: TCP
    name: http
    nodePort: 30007
  selector:
    app: {{ values.portalName }}-rhdh


