services:
  - type: web
    name: {{ values.portalName }}-rhdh
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_CONFIG_app_baseUrl
        sync: false
    healthCheckPath: /healthz


